ecommerce/urls.py
from django.urls import path, include
from mainapp import views


urlpatterns = [
    path('admin/', views.adminLogin, name="admin_login"),
    path('', include('mainapp.urls')),
]

mainapp/urls.py
from django.urls import path
from mainapp import AdminViews, views

urlpatterns = [
    path('admin/', views.adminLogin, name="admin_login"),
    path('admin_login_process', views.adminLoginProcess, name="admin_login_process"),
    path('admin_logout_process', views.adminLogoutProcess, name="admin_logout_process"),

    # PAGE FOR ADMIN
    path('admin_home', AdminViews.admin_home, name="admin_home"),

    # CATEGORIES
    path('category_list', AdminViews.CategoriesListView.as_view(), name="category_list"),
    path('category_create', AdminViews.CategoriesCreate.as_view(), name="category_create"),
    path('category_update/<slug:pk>', AdminViews.CategoriesUpdate.as_view(), name="category_update"),

    # SUBCATEGORIES

    path('sub_category_list', AdminViews.SubCategoriesListView.as_view(), name="sub_category_list"),
    path('sub_category_create', AdminViews.SubCategoriesCreate.as_view(), name="sub_category_create"),
    path('sub_category_update/<slug:pk>', AdminViews.SubCategoriesUpdate.as_view(), name="sub_category_update"),

    # Merchant User
    path('merchant_create', AdminViews.MerchantUserCreateView.as_view(), name="merchant_create"),
    path('merchant_list', AdminViews.MerchantUserListView.as_view(), name="merchant_list"),
    path('merchant_update/<slug:pk>', AdminViews.MerchantUserUpdateView.as_view(), name="merchant_update"),

    # Products
    path('product_create', AdminViews.ProductView.as_view(), name="product_view"),
    path('product_list', AdminViews.ProductListView.as_view(), name="product_list"),
    path('product_edit/<str:product_id>', AdminViews.ProductEdit.as_view(), name="product_edit"),
    path('product_add_media/<str:product_id>', AdminViews.ProductAddMedia.as_view(), name="product_add_media"),
    path('product_edit_media/<str:product_id>', AdminViews.ProductEditMedia.as_view(), name="product_edit_media"),
    path('product_media_delete/<str:id>', AdminViews.ProductMediaDelete.as_view(), name="product_media_delete"),
    path('product_add_stocks/<str:product_id>', AdminViews.ProductAddStocks.as_view(), name="product_add_stocks"),
    path('file_upload', AdminViews.file_upload, name="file_upload"),

    # Staff User
    path('staff_create', AdminViews.StaffUserCreateView.as_view(), name="staff_create"),
    path('staff_list', AdminViews.StaffUserListView.as_view(), name="staff_list"),
    path('staff_update/<slug:pk>', AdminViews.StaffUserUpdateView.as_view(), name="staff_update"),

    # Customer User
    path('customer_create', AdminViews.CustomerUserCreateView.as_view(), name="customer_create"),
    path('customer_list', AdminViews.CustomerUserListView.as_view(), name="customer_list"),
    path('customer_update/<slug:pk>', AdminViews.CustomerUserUpdateView.as_view(), name="customer_update"),

]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse


# Create your models here.
class CustomUser(AbstractUser):
    user_type_choices = ((1, "Admin"), (2, "Staff"), (3, "Merchant"), (4, "Customer"))
    user_type = models.CharField(max_length=255, choices=user_type_choices, default=1)


class AdminUser(models.Model):
    profile_pic = models.FileField(default="")
    auth_user_id = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class StaffUser(models.Model):
    profile_pic = models.FileField(default="")
    auth_user_id = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class MerchantUser(models.Model):
    auth_user_id = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    profile_pic = models.FileField(default="")
    company_name = models.CharField(max_length=255)
    gst_details = models.CharField(max_length=255)
    address = models.TextField()
    is_added_by_admin = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class CustomerUser(models.Model):
    auth_user_id = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    profile_pic = models.FileField(default="")
    created_at = models.DateTimeField(auto_now_add=True)


class Categories(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    url_slug = models.CharField(max_length=255)
    thumbnail = models.FileField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)

    def get_absolute_url(self):
        return reverse("category_list")

    def __str__(self):
        return self.title


class SubCategories(models.Model):
    id = models.AutoField(primary_key=True)
    category_id = models.ForeignKey(Categories, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    url_slug = models.CharField(max_length=255)
    thumbnail = models.FileField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)

    def get_absolute_url(self):
        return reverse("sub_category_list")


class Products(models.Model):
    id = models.AutoField(primary_key=True)
    url_slug = models.CharField(max_length=255)
    subcategories_id = models.ForeignKey(SubCategories, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=255)
    brand = models.CharField(max_length=255)
    product_max_price = models.CharField(max_length=255)
    product_discount_price = models.CharField(max_length=255)
    product_description = models.TextField()
    product_long_description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    added_by_merchant = models.ForeignKey(MerchantUser, on_delete=models.CASCADE)
    in_stock_total = models.IntegerField(default=1)
    is_active = models.IntegerField(default=1)


class ProductMedia(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    media_type_choice = ((1, "Image"), (2, "Video"))
    media_type = models.CharField(max_length=255)
    media_content = models.FileField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductTransaction(models.Model):
    id = models.AutoField(primary_key=True)
    transaction_type_choices = ((1, "BUY"), (2, "SELL"))
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    transaction_product_count = models.IntegerField(default=1)
    transaction_type = models.CharField(choices=transaction_type_choices, max_length=255)
    transaction_description = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)


class ProductDetails(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    title_details = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductAbout(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductTags(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductQuestions(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    user_id = models.ForeignKey(CustomerUser, on_delete=models.CASCADE)
    question = models.TextField()
    answer = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductReviews(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    user_id = models.ForeignKey(CustomerUser, on_delete=models.CASCADE)
    review_image = models.FileField()
    rating = models.CharField(default="5", max_length=255)
    review = models.TextField(default="")
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductReviewVoting(models.Model):
    id = models.AutoField(primary_key=True)
    product_review_id = models.ForeignKey(ProductReviews, on_delete=models.CASCADE)
    user_id_voting = models.ForeignKey(CustomerUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)


class ProductVarient(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)


class ProductVarientItems(models.Model):
    id = models.AutoField(primary_key=True)
    product_varient_id = models.ForeignKey(ProductVarient, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)


class CustomerOrders(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.DO_NOTHING)
    purchase_price = models.CharField(max_length=255)
    coupon_code = models.CharField(max_length=255)
    discount_amt = models.CharField(max_length=255)
    product_status = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)


class OrderDeliveryStatus(models.Model):
    id = models.AutoField(primary_key=True)
    order_id = models.ForeignKey(CustomerOrders, on_delete=models.CASCADE)
    status = models.CharField(max_length=255)
    status_message = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == 1:
            AdminUser.objects.create(auth_user_id=instance)
        if instance.user_type == 2:
            StaffUser.objects.create(auth_user_id=instance)
        if instance.user_type == 3:
            MerchantUser.objects.create(auth_user_id=instance, company_name="", gst_details="", address="")
        if instance.user_type == 4:
            CustomerUser.objects.create(auth_user_id=instance)


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.adminuser.save()
    if instance.user_type == 2:
        instance.staffuser.save()
    if instance.user_type == 3:
        instance.merchantuser.save()
    if instance.user_type == 4:
        instance.customeruser.save()

templates/admin_templates/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>
      {% block title %}
      {% endblock title %}
  </title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static '/modules/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/modules/fontawesome/css/all.min.css' %}">

  <!-- CSS Libraries -->
  <link rel="stylesheet" href="{% static '/modules/jqvmap/dist/jqvmap.min.css' %}">
  <link rel="stylesheet" href="{% static '/modules/weather-icon/css/weather-icons.min.css' %}">
  <link rel="stylesheet" href="{% static '/modules/weather-icon/css/weather-icons-wind.min.css' %}">
  <link rel="stylesheet" href="{% static '/modules/summernote/summernote-bs4.css' %}">

  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static '/css/style.css' %}">
  <link rel="stylesheet" href="{% static '/css/components.css' %}">

  {% block custom_css %}
  {% endblock custom_css %}

  <style>
  ul.errorlist{
    margin:0px;
  }
  .no-margin{
    margin:0px;
  }
  </style>
<!-- /END GA --></head>

<body>
  <div id="app">
    <div class="main-wrapper main-wrapper-1">
      {% include 'admin_templates/navbar.html' %}
      {% include 'admin_templates/sidebar.html' with id=form.instance.id %}
   

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>{% block page_title %}{% endblock page_title %}</h1>
          </div>
          {% if messages %}
          {% for message in messages %}
          {% if message.tags == "success" %}
          <div class="alert alert-success">
          {{ message }}
          </div>
          {% endif %}
          {% if message.tags == "error" %}
          <div class="alert alert-danger">
          {{ message }}
          </div>
          {% endif %}
          {% endfor %}
          {% endif %}
        {% block page_content %}
        {% endblock page_content %}
      </div>
      <footer class="main-footer">
        <div class="footer-left">
          Copyright &copy; 2021 <div class="bullet"></div>  SuperCodersStore 
        </div>
        <div class="footer-right">
          
        </div>
      </footer>
    </div>
  </div>

  <!-- General JS Scripts -->
  <script src="{% static '/modules/jquery.min.js' %}"></script>
  <script src="{% static '/modules/popper.js' %}"></script>
  <script src="{% static '/modules/tooltip.js' %}"></script>
  <script src="{% static '/modules/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static '/modules/nicescroll/jquery.nicescroll.min.js' %}"></script>
  <script src="{% static '/modules/moment.min.js' %}"></script>
  <script src="{% static '/js/stisla.js' %}"></script>
  
  <!-- JS Libraies -->
  <script src="{% static '/modules/simple-weather/jquery.simpleWeather.min.js' %}"></script>
  <script src="{% static '/modules/chart.min.js' %}"></script>
  <script src="{% static '/modules/jqvmap/dist/jquery.vmap.min.js' %}"></script>
  <script src="{% static '/modules/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
  <script src="{% static '/modules/summernote/summernote-bs4.js' %}"></script>
  <script src="{% static '/modules/chocolat/dist/js/jquery.chocolat.min.js' %}"></script>

  <!-- Page Specific JS File -->
  <script src="{% static '/js/page/index-0.js' %}"></script>
  
  <!-- Template JS File -->
  <script src="{% static '/js/scripts.js' %}"></script>
  <script src="{% static '/js/custom.js' %}"></script>
  {% block custom_js %}
  {% endblock custom_js %}
  <script>
    document.getElementById("title").onkeyup=function(){
      document.getElementById("url_slug").value=document.getElementById("title").value.toLowerCase().replaceAll(" ","-");
    }
  </script>
</body>
</html>

templates/admin_templates/category_create.html
{% extends 'admin_templates/base_template.html' %}
{% block title %}
Category Create
{% endblock title %}


{% block custom_css %}
{% endblock custom_css %}

{% block page_title %}
Category Create
{% endblock page_title %}

{% block page_content %}

<div class="row">
<div class="col-12 col-md-12 col-lg-12">
<div class="card">
    <div class="card-header">
    <h4>Categories</h4>
    </div>
    <div class="card-body">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label>{{ field.label }}</label>
            <input type="{{ field.field.widget.input_type }}" name={{ field.name }} id="{{ field.name }}" class="form-control">
            {% if field.errors %}
            <div class="alert alert-danger" style="margin:10px">
                {{ field.errors }}
            </div>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary btn-block">SAVE CATEGORY</button>
    </form>
</div>
</div>
</div>
{% endblock page_content %}


{% block custom_js %}
{% endblock custom_js %}

templates/admin_templates/customer_create.html
{% extends 'admin_templates/base_template.html' %}
{% block title %}
Customer Create
{% endblock title %}


{% block custom_css %}
{% endblock custom_css %}

{% block page_title %}
Customer Create
{% endblock page_title %}

{% block page_content %}

<div class="row">
<div class="col-12 col-md-12 col-lg-12">
<div class="card">
    <div class="card-header">
    <h4>Customer Users</h4>
    </div>
    <div class="card-body">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label>{{ field.label }}</label>
            <input type="{{ field.field.widget.input_type }}" name={{ field.name }} id="{{ field.name }}" class="form-control">
            {% if field.errors %}
            <div class="alert alert-danger" style="margin:10px">
                {{ field.errors }}
            </div>
            {% endif %}
        </div>
        {% endfor %}
         <div class="form-group">
            <label>Profile Image</label>
            <input type="file" name="profile_pic" id="profile_pic" class="form-control">
        </div>

  


        <button type="submit" class="btn btn-primary btn-block">SAVE CUSTOMER USER</button>
    </form>
</div>
</div>
</div>
</div>
{% endblock page_content %}


{% block custom_js %}
{% endblock custom_js %}

templates/admin_templates/customer_list.html
{% extends 'admin_templates/base_template.html' %}
{% block title %}
Customer User List
{% endblock title %}


{% block custom_css %}
{% endblock custom_css %}

{% block page_title %}
Customer User List
{% endblock page_title %}

{% block page_content %}
<div class="row">
    <div class="col-lg-12">
        <div class="search-element">
        <div class="card">
                  
                  <div class="card-body">
                  <form method="get">
                    <button class="btn  btn-primary" type="submit" style="float:right"><i class="fas fa-search"></i> Search</button>
                    <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250" style="width: 250px;float:right" name="filter" value="{{ filter }}">
                   </form>
                  </div>
                  
                </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="search-element">
        <div class="card">
                  
            <div class="card-body">
                <b>Sort By : - </b>
                <a href="{% url 'customer_list' %}?filter={{ filter }}&orderby=id">ID</a>  | 
                <a href="{% url 'customer_list' %}?filter={{ filter }}&orderby=created_at">Newest</a> |  
                <a href="{% url 'customer_list' %}?filter={{ filter }}&orderby=auth_user_id__first_name">First Name</a> |
                <a href="{% url 'customer_list' %}?filter={{ filter }}&orderby=auth_user_id__username">Username</a> |
            </div>
        </div>
        </div>
    </div>
</div>
<div class="row">
{% for customeruser in customeruser_list %}
<div class="col-12 col-sm-6 col-md-6 col-lg-3">
    <article class="article article-style-b">
        <div class="article-header">
        <div class="article-image" data-background="{{ customeruser.profile_pic }}" style="background-image: url(&quot;assets/img/news/img13.jpg&quot;);">
        </div>
        <div class="article-badge">
            <div class="article-badge-item bg-danger"><i class="fas fa-fire"></i>{{ customeruser.auth_user_id.username }}</div>
        </div>
        </div>
        <div class="article-details">
        <p class="no-margin"><span class="badge badge-warning"><i class="fas fa-user-circle"></i> Name : {{ customeruser.auth_user_id.first_name }} {{ customeruser.auth_user_id.last_name }}</span></p>
        <p class="no-margin"><span class="badge badge-info"><i class="fas fa-envelope-o "></i> Email : {{ customeruser.auth_user_id.email }}</span></p>
        <div class="article-cta">
            <label class="custom-switch mt-2" style="float:left">
                        <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input" {% if customeruser.auth_user_id.is_active == 1 %}checked{% endif %}>
                        <span class="custom-switch-indicator"></span>
                        <span class="custom-switch-description">ACTIVE</span>
            </label>
            <a href="{% url 'customer_update' customeruser.auth_user_id.id %}" class="btn btn-warning">EDIT <i class="fas fa-chevron-right"></i></a>
        </div>
        </div>
    </article>
</div>
{% endfor %}
</div>
<div class="row">
<div class="col-lg-12">
<div class="card">
                 
                  <div class="card-body">
                    <nav aria-label="Page navigation example">
                      <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="{% url 'customer_list' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.previous_page_number }}">Previous</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                                <li class="page-item {% if i == page_obj.number %}active{% endif %}"><a class="page-link" href="{% url 'customer_list' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="{% url 'customer_list' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.next_page_number }}">Next</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        {% endif %}

                      </ul>
                    </nav>
                  </div>
                </div>
                </div>
</div>
{% endblock page_content %}


{% block custom_js %}
{% endblock custom_js %}

templates/admin_templates/navbar.html
{% load static %}
<div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
          </ul>
          <div class="search-element">
           
          </div>
        </form>
        <ul class="navbar-nav navbar-right">
    
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            <img alt="image" src="{% static '/img/avatar/avatar-1.png' %}" class="rounded-circle mr-1">
            <div class="d-sm-none d-lg-inline-block">Hi, {{ request.user.username }}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
              <div class="dropdown-title">Logged in 5 min ago</div>
              <a href="features-profile.html" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Profile
              </a>
              <a href="features-activities.html" class="dropdown-item has-icon">
                <i class="fas fa-bolt"></i> Activities
              </a>
              <a href="features-settings.html" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> Settings
              </a>
              <div class="dropdown-divider"></div>
              <a href="{% url 'admin_logout_process' %}" class="dropdown-item has-icon text-danger">
                <i class="fas fa-sign-out-alt"></i> Logout
              </a>
            </div>
          </li>
        </ul>
      </nav>

templates/admin_templates/sub_category_list.html
{% extends 'admin_templates/base_template.html' %}
{% block title %}
Sub Category List
{% endblock title %}


{% block custom_css %}
{% endblock custom_css %}

{% block page_title %}
Sub Category List
{% endblock page_title %}

{% block page_content %}
<div class="row">
    <div class="col-lg-12">
        <div class="search-element">
        <div class="card">
                  
                  <div class="card-body">
                  <form method="get">
                    <button class="btn  btn-primary" type="submit" style="float:right"><i class="fas fa-search"></i> Search</button>
                    <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250" style="width: 250px;float:right" name="filter" value="{{ filter }}">
                   </form>
                  </div>
                  
                </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="search-element">
        <div class="card">
                  
            <div class="card-body">
                <b>Sort By : - </b>
                <a href="{% url 'sub_category_list' %}?filter={{ filter }}&orderby=id">ID</a>  | 
                <a href="{% url 'sub_category_list' %}?filter={{ filter }}&orderby=title">Title</a> |  
                <a href="{% url 'sub_category_list' %}?filter={{ filter }}&orderby=description">Description</a> 
            </div>
        </div>
        </div>
    </div>
</div>
<div class="row">
{% for subcategory in subcategories_list %}
<div class="col-12 col-sm-6 col-md-6 col-lg-3">
    <article class="article article-style-b">
        <div class="article-header">
        <div class="article-image" data-background="/media/{{ subcategory.thumbnail }}" style="background-image: url(&quot;assets/img/news/img13.jpg&quot;);">
        </div>
        <div class="article-badge">
            <div class="article-badge-item bg-danger"><i class="fas fa-fire"></i>{{ subcategory.title }}</div>
        </div>
        </div>
        <div class="article-details">
        <p><span class="badge badge-primary">{{ subcategory.category_id.title }}</span></p>
        <p>{{ subcategory.description }}</p>
        <p><span class="badge badge-warning">Url Slug : {{ subcategory.url_slug }}</span></p>
        <div class="article-cta">
            <label class="custom-switch mt-2" style="float:left">
                        <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input" {% if subcategory.is_active == 1 %}checked{% endif %}>
                        <span class="custom-switch-indicator"></span>
                        <span class="custom-switch-description">ACTIVE</span>
            </label>
            <a href="{% url 'sub_category_update' subcategory.id %}" class="btn btn-warning">EDIT <i class="fas fa-chevron-right"></i></a>
        </div>
        </div>
    </article>
</div>
{% endfor %}
</div>
<div class="row">
<div class="col-lg-12">
<div class="card">
                 
                  <div class="card-body">
                    <nav aria-label="Page navigation example">
                      <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="{% url 'sub_category_list' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.previous_page_number }}">Previous</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                                <li class="page-item {% if i == page_obj.number %}active{% endif %}"><a class="page-link" href="{% url 'sub_category_list' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="{% url 'sub_category_list' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.next_page_number }}">Next</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        {% endif %}

                      </ul>
                    </nav>
                  </div>
                </div>
                </div>
</div>

{% endblock page_content %}


{% block custom_js %}
{% endblock custom_js %}